language: objective-c
osx_image: xcode8

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
    - pod lib lint
    - xcbuild -workspace AFWebViewController.xcworkspace -scheme 'AFWebViewController' -sdk iphonesimulator build
